// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFLjtxXPZypWWJt9KJ8ST8ZFxkLfUw9GI',
    appId: '1:453053012589:web:7085d8464a0cbcfa85fd64',
    messagingSenderId: '453053012589',
    projectId: 'food-ordering-system-cb3b7',
    authDomain: 'food-ordering-system-cb3b7.firebaseapp.com',
    storageBucket: 'food-ordering-system-cb3b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhg8ZfdLJJeCz2_OYZmtnONkMPiEi9LnA',
    appId: '1:453053012589:android:51cbe357fb82999d85fd64',
    messagingSenderId: '453053012589',
    projectId: 'food-ordering-system-cb3b7',
    storageBucket: 'food-ordering-system-cb3b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3UM4ITanO8IWjy5BH28q8ZUkMTEnlKw',
    appId: '1:453053012589:ios:1cf05656f036a0b885fd64',
    messagingSenderId: '453053012589',
    projectId: 'food-ordering-system-cb3b7',
    storageBucket: 'food-ordering-system-cb3b7.appspot.com',
    iosBundleId: 'com.example.foodAdmin',
  );
}
